---
# ================================================================================================ #
#                                      ALIBABA SUBSAMPLE                                           #
# ================================================================================================ #

dag_no: 2
dag_name: alibaba_subsample
dag_description: Samples the Alibaba Data to Last n Days of Impressions
tasks:
  # ============================================================================================ #
  #                                     SAMPLE IMPRESSIONS                                       #
  # ============================================================================================ #
  1:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 1
    task_name: read_staged_impressions_data
    task_description: Read Staged Impressions Data
    task_params:
      dataset: alibaba
      name: impression
      stage: staged
      format: parquet
      mode: prod

  2:
    task: TimeSeriesSampler
    module: deepctr.dag.data_operators
    task_no: 2
    task_name: sample_production_impressions_data
    task_description: Sample Production Impressions Data
    task_params:
      start: alibaba
      name: impression
      stage: staged
      format: parquet

  # ============================================================================================ #
  #                                       USER                                                   #
  # ============================================================================================ #

  6:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 6
    task_name: read_alibaba_user_csv
    task_description: Read Alibaba User CSV
    task_params:
      dataset: alibaba
      name: user_profile
      stage: raw
      format: csv

  7:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 7
    task_name: replace_alibaba_user_column_names
    task_description: Replace Alibaba User Column Names
    task_params:
      columns:
        userid: user_id
        cms_segid: cms_segment_id
        cms_group_id: cms_group_id
        final_gender_code: gender_code
        age_level: age_level
        pvalue_level: consumption_level
        shopping_level: shopping_level
        occupation: student
        new_user_class_level: city_level

  8:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 8
    task_name: stage_user_data
    task_description: Stage User Data
    task_params:
      dataset: alibaba
      name: user
      stage: staged
      format: parquet


  # ============================================================================================ #
  #                                         AD                                                   #
  # ============================================================================================ #
  9:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 9
    task_name: read_alibaba_ad_csv
    task_description: Read Alibaba Ad CSV
    task_params:
      dataset: alibaba
      name: ad_feature
      stage: raw
      format: csv

  10:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 10
    task_name: transform_alibaba_ad_column_names
    task_description: Transform Alibaba Ad Column Names
    task_params:
      columns:
        adgroup_id: adgroup_id
        cate_id: category_id
        campaign_id: campaign_id
        customer: customer_id
        brand: brand_id
        price: price

  11:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 11
    task_name: stage_ad_data
    task_description: Stage Ad Data
    task_params:
      dataset: alibaba
      name: ad
      stage: staged
      format: parquet


  # ============================================================================================ #
  #                                  BEHAVIOR                                                    #
  # ============================================================================================ #
  12:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 12
    task_name: read_alibaba_behavior_csv
    task_description: Read Alibaba Behavior CSV
    task_params:
      dataset: alibaba
      name: behavior_log
      stage: raw
      format: csv

  13:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 13
    task_name: transform_alibaba_behavior_column_names
    task_description: Transform Alibaba Behavior Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        btag: btag
        cate: category_id
        brand: brand_id

  14:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 14
    task_name: stage_behavior_data
    task_description: Stage Behavior Data
    task_params:
      dataset: alibaba
      name: behavior
      stage: staged
      format: parquet



