---
# ================================================================================================ #
#                                         ALIBABA                                                  #
# ================================================================================================ #

dag_no: 2
dag_name: alibaba_etl
dag_description: Extracts, transforms and loads the Alibaba Display Ad Data (Production) from Amazon S3
resources:
  database:
    - mysql
    - alibaba
  cloud:
    - amazon
tasks:
  # ============================================================================================ #
  #                                     EXTRACT                                                  #
  # ============================================================================================ #
  1:
    task: ExtractS3
    module: deepctr.operators.remote
    task_no: 1
    task_name: extract_s3_data
    task_description: Extracts Alibaba Display Ad Data (Production) from Amazon S3
    task_params:
      bucket: deepctr
      folder: data/alibaba/production/external
      destination: data/alibaba/production/external
      external_resource:
        resource_type: cloud
        resource: amazon
      force: False
  2:
    task: ExpandGZ
    module: deepctr.operators.data
    task_no: 2
    task_name: expand_gzfiles
    task_description: Expands Alibaba Display Ad Data (Production) to raw directory
    task_params:
      source: data/alibaba/production/external
      destination: data/alibaba/production/raw
      force: False

  # ============================================================================================ #
  #                                         TRANSFORM                                            #
  # ============================================================================================ #
  # -------------------------------------------------------------------------------------------- #
  #                                REPLACE COLUMN NAMES                                          #
  #                            RAW SAMPLE FILE -> IMPRESSIONS                                    #
  # -------------------------------------------------------------------------------------------- #

  3:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 3
    task_name: read_alibaba_raw_sample_csv
    task_description: Read Alibaba Raw Sample CSV
    task_params:
      source: data/alibaba/production/raw/raw_sample.csv

  4:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 4
    task_name: replace_alibaba_raw_sample_column_names
    task_description: Replace Alibaba Raw Sample Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        adgroup_id: adgroup_id
        pid: scenario
        nonclk: non_click
        clk: click

  5:
    task: CSVWriter
    module: deepctr.operators.io
    task_no: 5
    task_name: write_alibaba_impression_csv
    task_description: Write Alibaba Impression CSV
    task_params:
      destination: data/alibaba/production/transformed/impression.csv

  # -------------------------------------------------------------------------------------------- #
  #                                REPLACE COLUMN NAMES                                          #
  #                                  USER FILE -> USER                                           #
  # -------------------------------------------------------------------------------------------- #

  6:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 6
    task_name: read_alibaba_user_csv
    task_description: Read Alibaba User CSV
    task_params:
      source: data/alibaba/production/raw/user_profile.csv

  7:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 7
    task_name: replace_alibaba_user_column_names
    task_description: Replace Alibaba User Column Names
    task_params:
      columns:
        userid: user_id
        cms_segid: cms_segment_id
        cms_group_id: cms_group_id
        final_gender_code: gender_code
        age_level: age_level
        pvalue_level: consumption_level
        shopping_level: shopping_level
        occupation: student
        new_user_class_level: city_level

  8:
    task: CSVWriter
    module: deepctr.operators.io
    task_no: 8
    task_name: write_alibaba_user_csv
    task_description: Write Alibaba User CSV
    task_params:
      destination: data/alibaba/production/transformed/user.csv
  # -------------------------------------------------------------------------------------------- #
  #                                  REPLACE COLUMN NAMES                                        #
  #                                      AD -> AD                                                #
  # -------------------------------------------------------------------------------------------- #
  9:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 9
    task_name: read_alibaba_ad_csv
    task_description: Read Alibaba Ad CSV
    task_params:
      source: data/alibaba/production/raw/ad_feature.csv

  10:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 10
    task_name: transform_alibaba_ad_column_names
    task_description: Transform Alibaba Ad Column Names
    task_params:
      columns:
        adgroup_id: adgroup_id
        cate_id: category_id
        campaign_id: campaign_id
        customer: customer_id
        brand: brand_id
        price: price

  11:
    task: CSVWriter
    module: deepctr.operators.io
    task_no: 11
    task_name: write_alibaba_ad_csv
    task_description: Write Alibaba Ad CSV
    task_params:
      destination: data/alibaba/production/transformed/ad.csv

  # -------------------------------------------------------------------------------------------- #
  #                                  REPLACE COLUMN NAMES                                        #
  #                                 BEHAVIORS -> BEHAVIORS                                       #
  # -------------------------------------------------------------------------------------------- #
  12:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 12
    task_name: read_alibaba_behaviors_csv
    task_description: Read Alibaba Behaviors CSV
    task_params:
      source: data/alibaba/production/raw/behavior_log.csv

  13:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 13
    task_name: transform_alibaba_behavior_column_names
    task_description: Transform Alibaba Behavior Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        btag: btag
        cate: category_id
        brand: brand_id

  14:
    task: CSVWriter
    module: deepctr.operators.io
    task_no: 14
    task_name: write_alibaba_behavior_csv
    task_description: Write Alibaba Behavior CSV
    task_params:
      destination: data/alibaba/production/transformed/behavior.csv

  # ============================================================================================ #
  #                                           LOAD                                               #
  # ============================================================================================ #

  # -------------------------------------------------------------------------------------------- #
  #                                    IMPRESSION TABLE                                          #
  # -------------------------------------------------------------------------------------------- #
  17:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 17
    task_name: read_alibaba_impression_data
    task_description: Read Alibaba Impression Data CSV
    task_params:
      source: data/alibaba/production/transformed/impression.csv

  18:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 18
    task_name: load_alibaba_impression_table
    task_description: Load Alibaba Impression Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: impression
      dtypes:
        user_id: Integer
        timestamp: BigInteger
        adgroup_id: Integer
        scenario: String(16)
        click: Integer

  # -------------------------------------------------------------------------------------------- #
  #                                      USER TABLE                                              #
  # -------------------------------------------------------------------------------------------- #
  19:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 19
    task_name: read_alibaba_user_data
    task_description: Read Alibaba User Data CSV
    task_params:
      source: data/alibaba/production/transformed/user.csv

  20:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 20
    task_name: load_alibaba_user_table
    task_description: Load Alibaba User Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: user
      dtypes:
        user_id: Integer
        cms_segment_id: Integer
        cms_group_id: Integer
        gender_code: Integer
        age_level: Integer
        consumption_level: Float
        shopping_level: Float
        student: Integer
        city_level: Float

  # -------------------------------------------------------------------------------------------- #
  #                                       AD TABLE                                               #
  # -------------------------------------------------------------------------------------------- #
  21:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 21
    task_name: read_alibaba_ad_data
    task_description: Read Alibaba Ad Data CSV
    task_params:
      source: data/alibaba/production/transformed/ad.csv

  22:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 22
    task_name: load_alibaba_ad_table
    task_description: Load Alibaba Ad Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: ad
      dtypes:
        adgroup_id: Integer
        campaign_id: Integer
        customer_id: Integer
        category_id: Integer
        brand: Float
        price: Float

  # -------------------------------------------------------------------------------------------- #
  #                                    BEHAVIOR TABLE                                            #
  # -------------------------------------------------------------------------------------------- #
  23:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 23
    task_name: read_alibaba_behavior_data
    task_description: Read Alibaba Behavior Data CSV
    task_params:
      source: data/alibaba/production/transformed/behavior.csv

  24:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 24
    task_name: load_alibaba_behavior_table
    task_description: Load Alibaba Behavior Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: behavior
      dtypes:
        user_id: Integer
        timestamp: BigInteger
        btag: String(8)
        category_id: Integer
        brand: Float
