---
# ================================================================================================ #
#                                      ALIBABA ETL                                                 #
# ================================================================================================ #

dag_no: 1
dag_name: alibaba_etl
dag_description: Extracts, transforms and loads the Alibaba Display Ad Data from Amazon S3
context:
  source: alibaba
  dataset: vesuvio
  home: data
  force: False
  s3_folders:
    vesuvio: alibaba/vesuvio
    trieste: alibaba/trieste
    kerouac: alibaba/kerouac

tasks:
  # ============================================================================================ #
  #                                     EXTRACT                                                  #
  # ============================================================================================ #
  1:
    task: ExtractS3
    module: deepctr.dag.data_operators
    task_no: 1
    task_name: extract_s3_data
    task_description: Extracts Alibaba Display Ad Data from Amazon S3
    task_params:
      home: data
      source: alibaba
      dataset: vesuvio
      bucket: deepctr
      stage: extract
      force: False
  2:
    task: ExpandGZ
    module: deepctr.dag.data_operators
    task_no: 2
    task_name: expand_gzfiles
    task_description: Expands Alibaba Display Ad Data (Production) to raw directory
    task_params:
      home: data
      source: alibaba
      dataset: vesuvio
      bucket: deepctr
      stage: extract
      force: False
      
      destination: data/test/alibaba/raw/alibaba_raw
      force: False

  # ============================================================================================ #
  #                            RAW SAMPLES -> IMPRESSIONS                                        #
  # ============================================================================================ #

  3:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 3
    task_name: read_alibaba_raw_sample_csv
    task_description: Read Alibaba Raw Sample CSV
    task_params:
      name: raw_sample
      stage: raw

  4:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 4
    task_name: replace_alibaba_raw_sample_column_names
    task_description: Replace Alibaba Raw Sample Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        adgroup_id: adgroup_id
        pid: scenario
        nonclk: non_click
        clk: click

  5:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 5
    task_name: stage_impression_data
    task_description: Stage Impression Data
    task_params:
      name: impression
      stage: staged



  # ============================================================================================ #
  #                                       USER                                                   #
  # ============================================================================================ #

  6:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 6
    task_name: read_alibaba_user_csv
    task_description: Read Alibaba User CSV
    task_params:
      name: user_profile
      stage: raw

  7:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 7
    task_name: replace_alibaba_user_column_names
    task_description: Replace Alibaba User Column Names
    task_params:
      columns:
        userid: user_id
        cms_segid: cms_segment_id
        cms_group_id: cms_group_id
        final_gender_code: gender_code
        age_level: age_level
        pvalue_level: consumption_level
        shopping_level: shopping_level
        occupation: student
        new_user_class_level: city_level

  8:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 8
    task_name: stage_user_data
    task_description: Stage User Data
    task_params:
      name: user
      stage: staged


  # ============================================================================================ #
  #                                         AD                                                   #
  # ============================================================================================ #
  9:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 9
    task_name: read_alibaba_ad_csv
    task_description: Read Alibaba Ad CSV
    task_params:
      name: ad_feature
      stage: raw

  10:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 10
    task_name: transform_alibaba_ad_column_names
    task_description: Transform Alibaba Ad Column Names
    task_params:
      columns:
        adgroup_id: adgroup_id
        cate_id: category_id
        campaign_id: campaign_id
        customer: customer_id
        brand: brand_id
        price: price

  11:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 11
    task_name: stage_ad_data
    task_description: Stage Ad Data
    task_params:
      name: ad
      stage: staged



  # ============================================================================================ #
  #                                  BEHAVIOR                                                    #
  # ============================================================================================ #
  12:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 12
    task_name: read_alibaba_behavior_csv
    task_description: Read Alibaba Behavior CSV
    task_params:
      name: behavior_log
      stage: raw

  13:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 13
    task_name: transform_alibaba_behavior_column_names
    task_description: Transform Alibaba Behavior Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        btag: btag
        cate: category_id
        brand: brand_id

  14:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 14
    task_name: stage_behavior_data
    task_description: Stage Behavior Data
    task_params:
      name: behavior
      stage: staged




