---
# ================================================================================================ #
#                                      ALIBABA ETL                                                 #
# ================================================================================================ #

dag_no: 1
dag_name: alibaba_etl
dag_description: Extracts, transforms and loads the Alibaba Display Ad Data from Amazon S3
tasks:
  # ============================================================================================ #
  #                                     DOWNLOAD                                                 #
  # ============================================================================================ #
  1:
    task: DownloadS3
    module: deepctr.dag.data_operators
    task_no: 1
    task_name: download_s3_data
    task_description: Downloads Alibaba Display Ad Data from Amazon S3
    task_params:
      source:
        name: vesuvio
        source: alibaba
        stage_id: 0
        stage_name: external
        storage_type: aws
        format: csv
        compressed: True
        bucket: deepctr
        folder: alibaba/vesuvio/
      destination:
        name: vesuvio
        source: alibaba
        stage_id: 0
        stage_name: external
        storage_type: local
        format: csv
        compressed: True
      force: False

  # ============================================================================================ #
  #                                      DECOMPRESS                                              #
  # ============================================================================================ #
  2:
    task: DecompressTARGZ
    module: deepctr.dag.data_operators
    task_no: 2
    task_name: decompresstargz
    task_description: Decompress tar.gz files 
    task_params:
      source:
        name: vesuvio
        source: alibaba
        stage_id: 0
        stage_name: external
        storage_type: local
        format: csv
        compressed: True
      destination:
        name: vesuvio
        source: alibaba
        stage_id: 0
        stage_name: external
        storage_type: local
        format: csv
        compressed: True
      force: False



  # ============================================================================================ #
  #                            RAW SAMPLES -> IMPRESSIONS                                        #
  # ============================================================================================ #

  2:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 2
    task_name: read_alibaba_raw_sample_csv
    task_description: Read Alibaba Raw Sample CSV
    task_params:
      file:
        home: data
        name: raw_sample
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: raw
        format: csv
      force: False

  3:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 3
    task_name: replace_alibaba_raw_sample_column_names
    task_description: Replace Alibaba Raw Sample Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        adgroup_id: adgroup_id
        pid: scenario
        nonclk: non_click
        clk: click

  4:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 4
    task_name: stage_impression_data
    task_description: Stage Impression Data
    task_params:
      file:
        home: data
        name: impression
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: staged
        format: parquet
      force: False


  # ============================================================================================ #
  #                                       USER                                                   #
  # ============================================================================================ #

  5:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 5
    task_name: read_alibaba_user_csv
    task_description: Read Alibaba User CSV
    task_params:
      file:
        home: data
        name: user_profile
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: raw
        format: csv
      force: False
  6:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 6
    task_name: replace_alibaba_user_column_names
    task_description: Replace Alibaba User Column Names
    task_params:
      columns:
        userid: user_id
        cms_segid: cms_segment_id
        cms_group_id: cms_group_id
        final_gender_code: gender_code
        age_level: age_level
        pvalue_level: consumption_level
        shopping_level: shopping_level
        occupation: student
        new_user_class_level: city_level

  7:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 7
    task_name: stage_user_data
    task_description: Stage User Data
    task_params:
      file:
        home: data
        name: user
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: staged
        format: parquet
      force: False


  # ============================================================================================ #
  #                                         AD                                                   #
  # ============================================================================================ #
  8:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 8
    task_name: read_alibaba_ad_csv
    task_description: Read Alibaba Ad CSV
    task_params:
      file:
        home: data
        name: ad_feature
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: raw
        format: csv
      force: False

  9:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 9
    task_name: transform_alibaba_ad_column_names
    task_description: Transform Alibaba Ad Column Names
    task_params:
      columns:
        adgroup_id: adgroup_id
        cate_id: category_id
        campaign_id: campaign_id
        customer: customer_id
        brand: brand_id
        price: price

  10:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 10
    task_name: stage_ad_data
    task_description: Stage Ad Data
    task_params:
      file:
        home: data
        name: ad
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: staged
        format: parquet
      force: False



  # ============================================================================================ #
  #                                  BEHAVIOR                                                    #
  # ============================================================================================ #
  11:
    task: DataReader
    module: deepctr.dag.data_operators
    task_no: 11
    task_name: read_alibaba_behavior_csv
    task_description: Read Alibaba Behavior CSV
    task_params:
      file:
        home: data
        name: behavior_log
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: raw
        format: csv
      force: False

  12:
    task: ReplaceColumnNames
    module: deepctr.dag.transform_operators
    task_no: 12
    task_name: transform_alibaba_behavior_column_names
    task_description: Transform Alibaba Behavior Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        btag: btag
        cate: category_id
        brand: brand_id

  13:
    task: DataWriter
    module: deepctr.dag.data_operators
    task_no: 13
    task_name: stage_behavior_data
    task_description: Stage Behavior Data
    task_params:
      file:
        home: data
        name: behavior
        dataset: vesuvio
        source: alibaba
        storage_type: local
        compressed: False
        stage: staged
        format: parquet
      force: False




