---
# ================================================================================================ #
#                                         ALIBABA                                                  #
# ================================================================================================ #

dag_no: 2
dag_name: alibaba_etl
dag_description: Extracts, transforms and loads the Alibaba Display Ad Data from Amazon S3
directories:
  dev: data/alibaba/development/
  prod: data/alibaba/raw/
resources:
  database:
    - alibaba
  cloud:
    - amazon
tasks:
  # ============================================================================================ #
  #                                     EXTRACT                                                  #
  # ============================================================================================ #
  1:
    task: ExtractS3
    module: deepctr.operators.remote
    task_no: 1
    task_name: extract_s3_data
    task_description: Extracts Alibaba Display Ad Data (Production) from Amazon S3
    task_params:
      bucket: deepctr
      folder: data/alibaba/external
      destination: data/alibaba/external
      external_resource:
        resource_type: cloud
        resource: amazon
      force: False
  2:
    task: ExpandGZ
    module: deepctr.operators.data
    task_no: 2
    task_name: expand_gzfiles
    task_description: Expands Alibaba Display Ad Data (Production) to raw directory
    task_params:
      source: data/alibaba/external
      destination: data/alibaba/raw
      force: False

  # ============================================================================================ #
  #                                CREATE DEVELOPMENT SET                                        #
  # ============================================================================================ #
  3:
    task: AlibabaDevSet
    module: deepctr.operators.data
    task_no: 3
    task_name: alibaba_devset_impression
    task_description: Creates impression development set
    task_params:
      dataset: impression
      source: data/alibaba/raw
      destination: data/alibaba/development
      sample_size: 20000
      header: True
      filename: raw_sample.csv
      random_state: 504
      force: False

  4:
    task: AlibabaDevSet
    module: deepctr.operators.data
    task_no: 4
    task_name: alibaba_devset_user
    task_description: Creates user development set
    task_params:
      dataset: user
      source: data/alibaba/raw
      destination: data/alibaba/development
      header: True
      filename: user_profile.csv
      force: False

  5:
    task: AlibabaDevSet
    module: deepctr.operators.data
    task_no: 5
    task_name: alibaba_devset_ad
    task_description: Creates ad development set
    task_params:
      dataset: ad
      source: data/alibaba/raw
      destination: data/alibaba/development
      header: True
      filename: ad_feature.csv
      force: False

  6:
    task: AlibabaDevSet
    module: deepctr.operators.data
    task_no: 6
    task_name: alibaba_devset_behavior
    task_description: Creates behavior development set
    task_params:
      dataset: behavior
      source: data/alibaba/raw
      destination: data/alibaba/development
      header: True
      filename: behavior_log.csv
      force: False

  # ============================================================================================ #
  #                                  DATABASE REFRESH                                            #
  # ============================================================================================ #

  7:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 7
    task_name: drop_existing_tables
    task_description: Drop tables if exist
    task_params:
      query: "DROP TABLE IF EXISTS user, impression, behavior, ad;"
      external_resource:
        resource_type: database
        resource: alibaba

  # ============================================================================================ #
  #                            RAW SAMPLES -> IMPRESSIONS                                        #
  # ============================================================================================ #

  8:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 8
    task_name: read_alibaba_raw_sample_csv
    task_description: Read Alibaba Raw Sample CSV
    task_params:
      filename: raw_sample.csv

  9:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 9
    task_name: replace_alibaba_raw_sample_column_names
    task_description: Replace Alibaba Raw Sample Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        adgroup_id: adgroup_id
        pid: scenario
        nonclk: non_click
        clk: click

  10:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 10
    task_name: load_alibaba_impression_table
    task_description: Load Alibaba Impression Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: impression
      dtypes:
        user_id: Integer
        timestamp: BigInteger
        adgroup_id: Integer
        scenario: String(16)
        click: Integer

  # ============================================================================================ #
  #                                       USER                                                   #
  # ============================================================================================ #

  11:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 11
    task_name: read_alibaba_user_csv
    task_description: Read Alibaba User CSV
    task_params:
      filename: user_profile.csv

  12:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 12
    task_name: replace_alibaba_user_column_names
    task_description: Replace Alibaba User Column Names
    task_params:
      columns:
        userid: user_id
        cms_segid: cms_segment_id
        cms_group_id: cms_group_id
        final_gender_code: gender_code
        age_level: age_level
        pvalue_level: consumption_level
        shopping_level: shopping_level
        occupation: student
        new_user_class_level: city_level

  13:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 13
    task_name: load_alibaba_user_table
    task_description: Load Alibaba User Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: user
      dtypes:
        user_id: Integer
        cms_segment_id: Integer
        cms_group_id: Integer
        gender_code: Integer
        age_level: Integer
        consumption_level: Float
        shopping_level: Float
        student: Integer
        city_level: Float

  # ============================================================================================ #
  #                                         AD                                                   #
  # ============================================================================================ #
  14:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 14
    task_name: read_alibaba_ad_csv
    task_description: Read Alibaba Ad CSV
    task_params:
      filename: ad_feature.csv

  15:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 15
    task_name: transform_alibaba_ad_column_names
    task_description: Transform Alibaba Ad Column Names
    task_params:
      columns:
        adgroup_id: adgroup_id
        cate_id: category_id
        campaign_id: campaign_id
        customer: customer_id
        brand: brand_id
        price: price

  16:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 16
    task_name: load_alibaba_ad_table
    task_description: Load Alibaba Ad Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: ad
      dtypes:
        adgroup_id: Integer
        campaign_id: Integer
        customer_id: Integer
        category_id: Integer
        brand_id: Float
        price: Float

  # ============================================================================================ #
  #                                  BEHAVIOR                                                    #
  # ============================================================================================ #
  17:
    task: CSVReader
    module: deepctr.operators.io
    task_no: 17
    task_name: read_alibaba_behaviors_csv
    task_description: Read Alibaba Behaviors CSV
    task_params:
      filename: behavior_log.csv

  18:
    task: ReplaceColumnNames
    module: deepctr.operators.data
    task_no: 18
    task_name: transform_alibaba_behavior_column_names
    task_description: Transform Alibaba Behavior Column Names
    task_params:
      columns:
        user: user_id
        time_stamp: timestamp
        btag: btag
        cate: category_id
        brand: brand_id

  19:
    task: TableLoader
    module: deepctr.operators.database
    task_no: 19
    task_name: load_alibaba_behavior_table
    task_description: Load Alibaba Behavior Table
    task_params:
      external_resource:
        resource_type: database
        resource: alibaba
      table: behavior
      dtypes:
        user_id: Integer
        timestamp: BigInteger
        btag: String(8)
        category_id: Integer
        brand_id: Float
