---
# ================================================================================================ #
#                                    ALIBABA DATABASE                                              #
# ================================================================================================ #

dag_no: 1
dag_name: alibaba_databae
dag_description: Builds Alibaba database backend
resources:
  database:
    - mysql
tasks:
  1:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 1
    task_name: foreign_key_check_off
    task_description: Disables foreign key checks
    task_params:
      query: "SET FOREIGN_KEY_CHECKS = 0;"
      external_resource:
        resource_type: database
        resource: mysql

  2:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 2
    task_name: drop_existing_tables
    task_description: Drop tables if exist
    task_params:
      query: "DROP TABLE IF EXISTS user, impression, behavior, ad;"
      external_resource:
        resource_type: database
        resource: mysql

  3:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 3
    task_name: drop_existing_database
    task_description: Drop alibaba database if it exists
    task_params:
      query: "DROP DATABASE IF EXISTS alibaba;"
      external_resource:
        resource_type: database
        resource: mysql

  4:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 4
    task_name: create_alibaba_database
    task_description: Create Alibaba database
    task_params:
      query: "CREATE DATABASE alibaba;"
      external_resource:
        resource_type: database
        resource: mysql

  5:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 5
    task_name: create_user_table
    task_description: Create User Table
    task_params:
      query: "CREATE TABLE user (user_id INT NOT NULL PRIMARY KEY,cms_segment_id INT,cms_group_id INT,gender_code INT,age_level INT,consumption_level DECIMAL(8,2),shopping_level INT,student INT,city_level DECIMAL(8,2)) ENGINE=InnoDB;"
      external_resource:
        resource_type: database
        resource: mysql

  6:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 6
    task_name: create_ad_table
    task_description: Create Ad Table
    task_params:
      query: "CREATE TABLE ad (adgroup_id INT NOT NULL PRIMARY KEY,campaign_id INT NOT NULL,   customer_id INT NOT NULL,   category_id INT NOT NULL,   brand DECIMAL(8,2),   price DECIMAL(8,2)) ENGINE=InnoDB;"
      external_resource:
        resource_type: database
        resource: mysql

  7:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 7
    task_name: create_behavior_table
    task_description: Create Behavior Table
    task_params:
      query: "CREATE TABLE behavior (user_id INT NOT NULL PRIMARY KEY,   timestamp BIGINT NOT NULL,   btag VARCHAR(8) NOT NULL,   category_id INT NOT NULL,   brand DECIMAL(8,2) NOT NULL, INDEX idx (user_id, timestamp)) ENGINE=InnoDB;"
      external_resource:
        resource_type: database
        resource: mysql

  8:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 8
    task_name: create_impression_table
    task_description: Create Impression Table
    task_params:
      query: "CREATE TABLE impression (user_id INT NOT NULL PRIMARY KEY,   timestamp BIGINT NOT NULL,   adgroup_id INT NOT NULL,   scenario VARCHAR(16) NOT NULL,   click INT NOT NULL, INDEX idx (user_id, timestamp),   INDEX agidx (adgroup_id), CONSTRAINT agidx FOREIGN KEY (adgroup_id)      REFERENCES ad(adgroup_id)       ON UPDATE CASCADE       ON DELETE CASCADE) ENGINE=InnoDB;"
      external_resource:
        resource_type: database
        resource: mysql

  9:
    task: SQLEngine
    module: deepctr.operators.database
    task_no: 9
    task_name: foreign_key_check_on
    task_description: Enable foreign key checks
    task_params:
      query: "SET FOREIGN_KEY_CHECKS = 1;"
      external_resource:
        resource_type: database
        resource: mysql
